name: 'Sync Specific Branches to Target Git Repository'
description: 'Synchronizes specified branches and tags to a target Git repository.'
author: 'Maximiliano Baez'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'git-branch'
  color: 'orange'